POST http://localhost:5000/api/phones
Content-Type: application/json

{
  "model": "iPhone 12",
  "brand": "Apple",
  "yearOfManufacture": "2020",
  "ramSize": "6",
  "processorId": "3",
  "screenSize": "6.2",
  "nfc": true
}