PATCH http://localhost:5000/api/phones/9 HTTP/1.1
Content-Type: application/json

{
  "model":"С90 T"
}

PATCH http://localhost:5000/api/phones/1000 HTTP/1.1
Content-Type: application/json

{
  "model":"С90 T"
}

PATCH http://localhost:5000/api/phones/9 HTTP/1.1
Content-Type: application/json

{
  "model":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
}